name: Deploy to CloudRun

on:
  push:
    branches:
      - main 

jobs:
  build:
    name: Cloud Run Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: 'latest'

      - name: Configure Docker
        run: |
          gcloud auth configure-docker
      
      - name: Build
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/signalb:latest .

      - name: Push
        run: |
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/signalb:latest

      - name: Deploy
        run: |
          gcloud run deploy signalb \
          --region asia-southeast1 \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/signalb \
          --cpu 3 \
          --memory 512Mi \
          --platform managed \
          --allow-unauthenticated \
          --set-env-vars DSN=${{ secrets.DSN }} \
          --set-env-vars RAPID_API_BASE_URL=${{ secrets.RAPID_API_BASE_URL }} \
          --set-env-vars RAPID_API_KEY=${{ secrets.RAPID_API_KEY }} \
          --set-env-vars RAPID_API_HOST=${{ secrets.RAPID_API_HOST }} \
          --set-env-vars TI_BASE_URL=${{ secrets.TI_BASE_URL }} \
          --set-env-vars TI_API_KEY=${{ secrets.TI_API_KEY }} \
          --set-env-vars COINAPI_BASE_URL=${{ secrets.COINAPI_BASE_URL }} \
          --set-env-vars COINAPI_API_KEY=${{ secrets.COINAPI_API_KEY }} \
          --set-env-vars TELEGRAM_API_TOKEN=${{ secrets.TELEGRAM_API_TOKEN }} \
          --set-env-vars TELEGRAM_CHAT_ID=${{ secrets.TELEGRAM_CHAT_ID }} \
          --set-env-vars GOMAXPROCS=2 \
          --min-instances 0
          --max-instances 1
          --project ${{ secrets.GCP_PROJECT_ID }}
