name: Refresh Data and Evaluate Strategies

on:
  schedule:
    - cron: '0 */4 * * *'  # Every 4 hours
    - cron: '0 23 * * *'    # Every day at midnight UTC
    - cron: '0 0 * * 0'    # Every Sunday at midnight UTC
    
env:
  REFRESH_DATA_H4_URL: ${{ secrets.REFRESH_DATA_H4_URL }}
  REFRESH_DATA_D1_URL: ${{ secrets.REFRESH_DATA_D1_URL }}
  REFRESH_DATA_W1_URL: ${{ secrets.REFRESH_DATA_W1_URL }}
  EVALUATE_STRATEGIES_H4_URL: ${{ secrets.EVALUATE_STRATEGIES_H4_URL }}
  EVALUATE_STRATEGIES_D1_URL: ${{ secrets.EVALUATE_STRATEGIES_D1_URL }}
  EVALUATE_STRATEGIES_W1_URL: ${{ secrets.EVALUATE_STRATEGIES_W1_URL }}
  
jobs:
  refresh-evaluate-h4:
    runs-on: ubuntu-latest

    steps:
      - name: Refresh Data for H4 Timeframe
        run: |
          curl -X POST $REFRESH_DATA_H4_URL

      - name: Evaluate Strategies for Tickers in H4 Timeframe
        run: |
          curl -X GET $EVALUATE_STRATEGIES_H4_URL

  refresh-evaluate-d1:
    runs-on: ubuntu-latest

    steps:
      - name: Refresh Data for D1 Timeframe
        run: |
          curl -X POST $REFRESH_DATA_D1_URL

      - name: Evaluate Strategies for Tickers in D1 Timeframe
        run: |
          curl -X GET $EVALUATE_STRATEGIES_D1_URL

  refresh-evaluate-W1:
    runs-on: ubuntu-latest

    steps:
      - name: Refresh Data for W1 Timeframe
        run: |
          curl -X POST $REFRESH_DATA_W1_URL

      - name: Evaluate Strategies for Tickers in W1 Timeframe
        run: |
          curl -X GET $EVALUATE_STRATEGIES_W1_URL
