name: Refresh Data and Evaluate Strategies D1

on:
  schedule:
    - cron: '0 23 * * *'    # Every day at 2300 UTC
    
env:
  REFRESH_DATA_D1_URL: ${{ secrets.REFRESH_DATA_D1_URL }}
  EVALUATE_STRATEGIES_D1_URL: ${{ secrets.EVALUATE_STRATEGIES_D1_URL }}
  
jobs:
  refresh-evaluate-d1:
    runs-on: ubuntu-latest

    steps:
      - name: Refresh Data for D1 Timeframe
        run: |
          curl -X POST $REFRESH_DATA_D1_URL

      - name: Evaluate Strategies for Tickers in D1 Timeframe
        run: |
          curl -X GET $EVALUATE_STRATEGIES_D1_URL